#!/bin/bash
set -e

LIMIT=${1:-30}
FILE=mcpi-limit.count
MINUTES=$LIMIT

# count file exists and modified today
if [[ -f "$FILE" && $(date -r "$FILE" -Idate) == $(date -Idate) ]]; then
  MINUTES=$(cat "$FILE")

  if [[ "$MINUTES" -lt 1 ]]; then
    ./mcpi-kill
  elif [[ "$MINUTES" -le 5 ]]; then
    ./mcpi-message "$MINUTES minutes left"
  else
    ./mcpi-message # checks if Minecraft is running
  fi

else
  ./mcpi-message "Welcome to Minecraft!"
fi
 
echo $(($MINUTES - 1)) > "$FILE"
